RazorAucionWebapp/Pages/AdminPages/Accounts/Detail.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualBasic;
using Repository.Database;
using Repository.Database.Model.AppAccount;
using Service.Services.AppAccount;

namespace RazorAucionWebapp.Pages.AdminPages.Accounts
{
    public class DetailModel : PageModel
    {
        private readonly AccountServices _accountServices;

        public DetailModel(AccountServices accountServices)
        {
            _accountServices = accountServices;
        }

        public Account Account { get; set; } = default!;
        [BindProperty]
        public int AccountId { get; set; }
        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null )
            {
                return NotFound();
            }
            try
            {
                await PopulateData(id.Value);
                return Page();
            }
            catch (Exception ex) 
            {
                return BadRequest(ex.Message);
            }

            
        }
        public async Task<IActionResult> OnPostBanAsync()
        {
            if(AccountId == 0) 
            {
                return NotFound();
            }
            try
            {
                await PopulateData(AccountId);
                var result = await _accountServices.AdminBanUser(Account);
                if(result.IsSuccess ) 
                {
                    return RedirectToPage("./Index");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, result.message);
                    return Page();
                }
            }
            catch (Exception ex) 
            {
                return BadRequest(ex.Message);
            }
        }
        public async Task<IActionResult> OnPostActiveAsync()
        {
            if (AccountId == 0)
            {
                return NotFound();
            }
            try
            {
                await PopulateData(AccountId);
                var result = await _accountServices.AdminActiveUser(Account);
                if (result.IsSuccess)
                {
                    return RedirectToPage("./Index");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, result.message);
                    return Page();
                }
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }
        private async Task PopulateData(int accountId)
        {
            Account = await _accountServices.GetById(accountId) ?? throw new Exception("cannot find id for this account");
        }
    }
}

RazorAucionWebapp/Pages/AdminPages/EstateCategories/Detail.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Repository.Database.Model.RealEstate;
using Service.Services.RealEstate;

namespace RazorAucionWebapp.Pages.AdminPages.EstateCategories
{
    public class DetailModel : PageModel
    {
        private readonly EstateCategoryDetailServices _estateCategoryDetailRepository;
        private readonly EstateCategoriesServices _estateCategoriesRepository;
        public DetailModel(EstateCategoryDetailServices estateCategoryDetailRepository, EstateCategoriesServices estateCategoriesRepository)
        {
            _estateCategoryDetailRepository = estateCategoryDetailRepository;
            _estateCategoriesRepository = estateCategoriesRepository;
        }
        
        public EstateCategoryDetail EstateCategoryDetail { get; set; } = default!;
        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if(id == null)
            {
                return RedirectToPage("./Index");
            }
            EstateCategoryDetail = await _estateCategoryDetailRepository.GetById(id.Value);
            return Page();
        }
        public async Task<IActionResult> OnPostAsync(int delId)
        {
            var flag = await DeleteCategory(delId);
            return RedirectToPage("./Index");
        }
        public async Task<bool> DeleteCategory(int id)
        {
            var flag1 = await _estateCategoriesRepository.CheckForCategoryDetailInUsed(id);
            if (!flag1)
            {
                var item = await _estateCategoryDetailRepository.GetById(id);
                var flag2 = await _estateCategoryDetailRepository.DeleteCategoryDetail(item);
                if (flag2)
                {
                    TempData["DelSuccess"] = String.Format("Category {0} removed!", item.CategoryName);
                    return true;
                }
                else
                {
                    TempData["DelFail"] = "Can't remove category due to database error!";
                }
            }
            else
            {
                TempData["DelFail"] = "Can't remove category due to it is still in use!";
            }
            return false;
        }
    }
}

RazorAucionWebapp/Pages/AdminPages/Revenue/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Repository.Database;
using Repository.Database.Model.AuctionRelated;

namespace RazorAucionWebapp.Pages.AdminPages.Revenue
{
    public class DetailsModel : PageModel
    {
        private readonly Repository.Database.AuctionRealEstateDbContext _context;

        public DetailsModel(Repository.Database.AuctionRealEstateDbContext context)
        {
            _context = context;
        }

      public AuctionReceipt AuctionReceipt { get; set; } = default!; 

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.AuctionReceipts == null)
            {
                return NotFound();
            }

            var auctionreceipt = await _context.AuctionReceipts.FirstOrDefaultAsync(m => m.ReceiptId == id);
            if (auctionreceipt == null)
            {
                return NotFound();
            }
            else 
            {
                AuctionReceipt = auctionreceipt;
            }
            return Page();
        }
    }
}

RazorAucionWebapp/Pages/CompanyPages/AuctionMng/Receipts/Detail.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Repository.Database;
using Repository.Database.Model.AuctionRelated;
using Service.Services.AppAccount;
using Service.Services.Auction;
using Service.Services.RealEstate;

namespace RazorAucionWebapp.Pages.CompanyPages.AuctionMng.Receipts
{
    public class DetailModel : PageModel
    {
        private readonly AuctionServices _auctionServices;
        private readonly EstateServices _estateServices;
        private readonly AccountServices _accountServices;
        private readonly AuctionReceiptPaymentServices _auctionReceiptPaymentServices;
        private readonly AuctionReceiptServices _auctionReceiptServices;
		public DetailModel(AuctionServices auctionServices, EstateServices estateServices, AccountServices accountServices, AuctionReceiptPaymentServices auctionReceiptPaymentServices, AuctionReceiptServices auctionReceiptServices)
		{
			_auctionServices = auctionServices;
			_estateServices = estateServices;
			_accountServices = accountServices;
			_auctionReceiptPaymentServices = auctionReceiptPaymentServices;
            _auctionReceiptServices = auctionReceiptServices;
		}

		public AuctionReceipt AuctionReceipt { get; set; } = default!; 
        public List<AuctionReceiptPayment> TransactionsForReceipt { get; set; }
        public async Task<IActionResult> OnGetAsync(int? auctionId)
        {
            if (auctionId == null)
            {
                return NotFound();
            }
            try
            {
                await PopulateData(auctionId.Value);
				return Page();
			}
			catch (Exception ex) 
            {
                Console.WriteLine(ex.Message);
                return Page();
            }
            
        }
        private async Task PopulateData(int auctionId) 
        {
            var tryGetReceipt = await _auctionReceiptServices.GetByAuctionId(auctionId, "Auction");
            if(tryGetReceipt == null) 
            {
                ModelState.AddModelError(string.Empty, "No receipt can be found for this auction");
                throw new NullReferenceException();
            }
            else
				AuctionReceipt = tryGetReceipt;			
			var tryGetReceiptTransaction = await _auctionReceiptPaymentServices.GetByReceiptId(tryGetReceipt.ReceiptId, "Account");
			if (tryGetReceiptTransaction == null)
			{
				ModelState.AddModelError(string.Empty, "No transaction can be found for this reeipt");
				throw new NullReferenceException();
			}else
                TransactionsForReceipt = tryGetReceiptTransaction;   
		}
    }
}

RazorAucionWebapp/Pages/CustomerPages/Profile/Update.cshtml.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorAucionWebapp.BackgroundServices;
using Repository.Database.Model;
using Service.Services.AppAccount;
using System.ComponentModel.DataAnnotations;
using System.Security.Claims;

namespace RazorAucionWebapp.Pages.CustomerPages
{
    public class UpdateModel : PageModel
    {
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly AccountImagesServices _accountImagesServices;
        private readonly AccountServices _accountServices;
        [BindProperty]
        public int Id {  get; set; }
        [BindProperty]
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Name is required")]
        public string Name { get; set; }
        [BindProperty]
        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "Email is required")]
        public string Email { get; set; }
        [BindProperty]
        [DataType(DataType.PhoneNumber)]
        [Required(ErrorMessage = "Phone number is required")]
        [RegularExpression(@"^0\d{9}$", ErrorMessage = "Phone number is not in correct format")]
        [StringLength(10, MinimumLength = 10, ErrorMessage = "Not valid phone number")]
        public string Tel { get; set; }
        [BindProperty]
        [DataType(DataType.Date)]
        public DateTime Dob { get; set; }
        [BindProperty]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Password is required")]
        public string Pass { get; set; }
        [BindProperty]
        public AppImage Image { get; set; }
        [BindProperty]
        public string Avatar { get; set; }
        public IFormFile ImageFile { get; set; }
        [BindProperty]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "NewPass is required")]
        public string NewPass { get; set; }
        public UpdateModel(IWebHostEnvironment webHostEnvironment, AccountImagesServices accountImagesServices, AccountServices accountServices)
        {
            _webHostEnvironment = webHostEnvironment;
            _accountServices = accountServices;
            _accountImagesServices = accountImagesServices;
        }
        public async Task<IActionResult> OnGetAsync()
        {
            var flag = await PopulateData();
            if (flag is false)
            {
                return RedirectToPage("/Registration/Login");
            }
            await GetAvatar();
            return Page();
        }
        public async Task<IActionResult> OnPostImageUpdateAsync()
        {
            if (ImageFile is not null)
            {
                var (directory, path) = GetAvatarDirectory();
                var result = await _accountImagesServices.Create(Id, path, "avatar.png");
                if (result.IsSuccess)
                {
                    ImageHandler.SaveImage(ImageFile, Path.Combine(directory, path), result.image.Name);
                    UpdateClaim("~/PublicImages/storage/" + result.image.Path);
                    TempData["Success"] = "Avatar updated";
                    return RedirectToPage("./Detail");
                }
                else TempData["Failed"] = "Unknown error has occured";
            }
            else TempData["Failed"] = "No image uploaded";
            await GetAvatar();
            return Page();
        }
        public async Task<IActionResult> OnPostUpdateAsync()
        {

            var flag = ModelState["Name"].Errors.Any() || ModelState["Email"].Errors.Any() || ModelState["Tel"].Errors.Any() || ModelState["Pass"].Errors.Any();
            if (!flag)
            {
                var account = await _accountServices.GetById(Id);
                if (account.Password.Equals(Pass))
                {
                    account.FullName = Name;
                    account.Email = Email;
                    account.Dob = Dob;
                    account.Telephone = Tel;
                    var result = await _accountServices.Update(account);
                    if (result)
                    {
                        TempData["Success"] = "Profile updated";
                        return RedirectToPage("./Detail");
                    }
                    else TempData["Failed"] = "Unknown error has occured";
                }
                else
                {
                    TempData["Pass"] = "Wrong password";
                }
            }
            else{
                TempData["Name"] = ModelState["Name"].Errors.FirstOrDefault()?.ErrorMessage;
                TempData["Email"] = ModelState["Email"].Errors.FirstOrDefault()?.ErrorMessage;
                TempData["Tel"] = ModelState["Tel"].Errors.FirstOrDefault()?.ErrorMessage;
                TempData["Dob"] = ModelState["Dob"].Errors.FirstOrDefault()?.ErrorMessage;
                TempData["Pass"] = ModelState["Pass"].Errors.FirstOrDefault()?.ErrorMessage;
            }
            await GetAvatar();
            return Page();
        }
        public async Task<IActionResult> OnPostChangeAsync()
        {
            var flag = ModelState["Pass"].Errors.Any() || ModelState["NewPass"].Errors.Any();
            if (!flag)
            {
                var account = await _accountServices.GetById(Id);
                if (account.Password.Equals(Pass))
                {
                    if (Pass != NewPass)
                    {
                        account.Password = NewPass;
                        var result = await _accountServices.Update(account);
                        if (result)
                        {
							TempData["Success"] = "Password changed";
                            return RedirectToPage("./Detail");
						}
                        else TempData["Failed"] = "Unknown error has occured";
                    }
                    else
                    {
                        TempData["NewPass"] = "New password can't be your old password.";
                    }
                }
                else
                {
                    TempData["Pass"] = "Wrong password";
                }
            }
            else
            {
                TempData["OldPass"] = ModelState["Pass"].Errors.FirstOrDefault().ErrorMessage;
                TempData["NewPass"] = ModelState["NewPass"].Errors.FirstOrDefault().ErrorMessage;
			}
            await GetAvatar();
            return RedirectToPage();
        }
        private async Task<bool> PopulateData()
        {
            var id = HttpContext.User.FindFirst("Id")?.Value;
            var result = int.TryParse(id, out int accountId);
            if (result)
            {
                var account = await _accountServices.GetById(accountId);
                Id = account.AccountId;
                Name = account.FullName;
                Email = account.Email;
                Tel = account.Telephone;
                Dob = account.Dob;
                return true;
            }
            return false;
        }
        private async Task<bool> GetAvatar()
        {
            Avatar = HttpContext.User.FindFirst("Avatar").Value;
            if (Avatar != "")
            {
                return true;
            }
            return false;
        }
        private (string,string) GetAvatarDirectory()
        {
            var email = HttpContext.User.FindFirst(ClaimTypes.Email)?.Value;
            if (email is not null)
            {
                email = ImageHandler.RemoveWhiteSpace(email);
                var directory = _webHostEnvironment.ContentRootPath;
                return (Path.Combine(directory.Replace("//","\\"), "wwwroot","PublicImages","storage"),Path.Combine("user", email));
            }
            else return (null, null);
        }

        private void UpdateClaim(string path)
        {
            var Identity = HttpContext.User.Identity as ClaimsIdentity;
            Identity.RemoveClaim(Identity.FindFirst("Avatar"));
            Identity.AddClaim(new Claim("Avatar", path));
        }
    }
}

RazorAucionWebapp/Pages/CustomerPages/Profile/Detail.cshtml
@page
@model RazorAucionWebapp.Pages.CustomerPages.Profile.DetailModel

@{
    ViewData["Title"] = "Detail";
}
@if (TempData["Success"] is not null)
{
    <div class="border border-2 m-3 p-3 text-success">
        @TempData["Success"]
    </div>
}
<div class="container">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">Home</li>
            <li class="breadcrumb-item">Customer account</li>
            <li class="breadcrumb-item"><a href="#">Profile</a></li>
        </ol>
    </nav>
    <div class="detailBtn">
        <a asp-page="../Transactions/Create">Fill your wallet</a>
        <a asp-page="./Update"><i class="fa-solid fa-pen-to-square"></i> Edit Profile</a>
    </div>
    <div class="profile_wrapper">
        <div class="row">
            <div class="col-md-3">
                <div class="left_profile">
                    <img class="rounded-circle" src=@Url.Content(Model.Avatar) height="40" width="40" />
                    <span class="fw-bold">User #@Model.Account.AccountId</span>
                </div>
            </div>
            <div class="col-md-9">
                <div class="right_profile">
                    <h5>User information</h5>
                    <hr />
                    <div class="row">
                        <div class="col-md-6">
                            <div class="info_text"><span>Full name</span>@Model.Account.FullName</div>
                        </div>
                        <div class="col-md-6">
                            <div class="info_text"><span>Phone</span>@Model.Account.Telephone</div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="info_text"><span>Email</span>@Model.Account.Email</div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="info_text"><span>Birthday</span> @Model.Account.Dob</div>
                        </div>
                        <div class="col-md-6">
                            <div class="info_text"><span>Citizen ID</span>@Model.Account.CMND</div>
                        </div>
                    </div>
                    <div>
                        <h6>Account</h6>
                        <hr />
                        <div class="row">
                            <div class="col-md-8">
                                Status:
                                @if (Model.Account.Status.ToString() == "PENDING")
                                {
                                    <p class="account_status_pending">@Model.Account.Status.ToString()</p>
                                }
                                else if (Model.Account.Status.ToString() == "ACTIVED")
                                {
                                    <p class="account_status_active">@Model.Account.Status.ToString()</p>

                                }
                                else
                                {
                                    <p class="account_status_deactivate">Status:@Model.Account.Status.ToString()</p>
                                }
                            </div>
                            <div class="col-md-4">
                                <p>Balance: <span class="fw-bold">$ @Model.Account.Balance</span></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

</div>

RazorAucionWebapp/Pages/CustomerPages/Profile/Update.cshtml
@page "{handler?}"
@using System.Security.Claims;
@model RazorAucionWebapp.Pages.CustomerPages.UpdateModel
@{
}

@if(TempData["Failed"] is not null)
{
    <div class="alert alert-danger">
        @TempData["Failed"]
    </div>
}
<div class="container">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">Home</li>
            <li class="breadcrumb-item">Customer account</li>
            <li class="breadcrumb-item">Profile</li>
            <li class="breadcrumb-item"><a href="#">Edit</a></li>
        </ol>
    </nav>
    <div class="row">
        <div class="col-md-12 d-flex justify-content-end">
            <button id="updateFormBtn" class="active_form_btn">Update Profile</button>
            <button id="changeFormBtn" class="inactive_form_btn">Change Password</button>
        </div>
    </div>

    <div class="profile_wrapper">
        <div class="row">
            <div class="col-md-3">
                <div class="left_profile">
                    <div class="user_img">
                        <div class="relative_user_img">
                            <img id="previewImg" src=@Url.Content(Model.Avatar) width="20" height="20" />
                            <label class="choose_img_btn" for="uploadImg"><i class="fa-solid fa-pencil"></i></label>
                            <a id="ImageUpdateConfirm" data-bs-toggle="modal" data-bs-target="#updateModal">Save image</a>
                        </div>
                        
                    </div>

                    <form method="post" id="avatarForm" asp-page-handler="ImageUpdate" enctype="multipart/form-data" style="display: none;">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="row my-2">
                            <input type="hidden" asp-for="Id" />
                            <input type="file" id="uploadImg" asp-for="ImageFile" accept=".png,.jpeg, .jpg" />
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-md-9">
                <div class="right_profile">
                    <h5 style="color: black;">User information</h5>
                    <hr />
                    <form method="post" id="updateForm" asp-page-handler="update">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <input type="hidden" asp-for="Id" />
                        <div class="row">
                            <div class="col-md-6">
                                @Html.DisplayNameFor(model => model.Name)<br />
                                <input asp-for="Name" />
                                <span class="text-danger">@TempData["Name"]</span>
                            </div>
                            <div class="col-md-6">
                                @Html.DisplayNameFor(model => model.Tel)<br />
                                <input asp-for="Tel" />
                                <span class="text-danger">@TempData["Email"]</span>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                @Html.DisplayNameFor(model => model.Email)<br />
                                <input asp-for="Email" />
                                <span class="text-danger">@TempData["Email"]</span>
                            </div>
                            <div class="col-md-6">
                                @Html.DisplayNameFor(model => model.Dob)<br />
                                <input asp-for="Dob" />
                                <span class="text-danger">@TempData["Dob"]</span>
                            </div>
                        </div>
                        <div class="row mt-3">
                            <div class="col-md-4"></div>
                            <div class="col-md-4">
                                <div>Type your password to confirm</div>
                                <input asp-for="Pass" />
                                <span class="text-danger">@TempData["Pass"]</span>
                                <div class="detailBtn">
                                    <a id="UpdateConfirm" class="btn btn-outline-info" data-bs-toggle="modal" data-bs-target="#updateModal">Save</a>
                                </div>
                            </div>
                        </div>
                    </form>
                    <form method="post" id="changeForm" asp-page-handler="change" style="display:none;">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <input type="hidden" asp-for="Id" />
                        <div>
                            <div>Old Password</div>
                            <input asp-for="@Model.Pass" />
                            <span class="text-danger">@TempData["OldPass"]</span>
                        </div>
                        <div>
                            <div>New Password</div>
                            <input asp-for="@Model.NewPass" />
                            <span asp-asp-validation-for="Model.NewPass" />
                            <span class="text-danger">@TempData["NewPass"]</span>
                        </div>
                        <br />
                        <div class="detailBtn">
                            <a id="ChangeConfirm" class="btn btn-outline-info" data-bs-toggle="modal" data-bs-target="#updateModal">Save</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>
<script>
    function ChangeImg(input){
        var reader = new FileReader();
        reader.onload = function(e){
            $("#previewImg").attr("src", e.target.result);
        }
        if(input.files[0] == null){
            $("#previewImg").hide();
        }
        else{
            $("#previewImg").show();
            reader.readAsDataURL(input.files[0]);
        }
    }

    $("#uploadImg").change(function(){
        ChangeImg(this);
    })

    $('#updateFormBtn').click(function(){
        $('#test').hide();
        $('#changeForm').hide();
        $('#updateForm').show();
        $('#updateFormBtn').attr('class', 'active_form_btn')
        $('#changeFormBtn').attr('class', 'inactive_form_btn')
    })
    $('#changeFormBtn').click(function () {
        $('#test').show();
        $('#changeForm').show();
        $('#updateForm').hide();
        $('#changeFormBtn').attr('class', 'active_form_btn')
        $('#updateFormBtn').attr('class', 'inactive_form_btn')
    })
    $('#sumbitImg').click(function () {
        console.log("clickeddd");
        $('#ImageUpdateConfirm').click();
    });
    $('#ImageUpdateConfirm').click(function () {
        $('#modal-desc').html('Are you sure to update your avatar?')
        $('#modal-confirm').attr('form', 'avatarForm')
    })
    $('#UpdateConfirm').click(function(){
        $('#modal-desc').html('Are you sure to update your information?')
        $('#modal-confirm').attr('form', 'updateForm')
    })
    $('#ChangeConfirm').click(function () {
        $('#modal-desc').html('Are you sure to change to the new password?')
        $('#modal-confirm').attr('form', 'changeForm')
    })
</script>
<div class="modal fade" id="updateModal" tabindex="-1" role="dialog" aria-labelledby="updateModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="updateModalLabel">Confirmation</h5>
            </div>
            <div class="modal-body">
                <span aria-hidden="true" id="modal-desc"></span>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <input type="submit" value="Confirm" form="" id="modal-confirm" class="btn btn-success"></input>
            </div>
        </div>
    </div>
</div>